on: 
  push:
    branches:
      - main

jobs:
  generate-and-apply-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate MachineConfig
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir quay.io/coreos/butane:latest butane ./fc/infoscale/99-master-fc-udev-infoscale.bu -o ./fc/infoscale/99-master-fc-udev-infoscale.yaml
