on: 
  push:
    branches:
      - main

jobs:
  generate-and-apply-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Butane CLI
        run: |
          pip install coreos-butane
          # Verify installation
          butane --version

      - name: Generate MachineConfig
        run: |
          butane 99-master-fc-udev-infoscale.bu -o 99-master-fc-udev-infoscale.yaml
          # Display the generated file content (optional)
          cat 99-master-fc-udev-infoscale.yaml
          
      - name: Upload MachineConfig Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 99-master-fc-udev-infoscale-yaml
          path: ./fc/infoscale/99-master-fc-udev-infoscale.yaml
