on: 
  push:
    branches:
      - main

jobs:
  generate-and-apply-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: List files in the workspace
        run: |
          ls -la ${{ github.workspace }}/fc/infoscale
        
      - name: Generate MachineConfig
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir quay.io/coreos/butane:latest butane --files-dir /workdir/fc/infoscale 99-master-fc-udev-infoscale.bu -o 99-master-fc-udev-infoscale.yaml
          

